//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitectureReferenceTemplate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitectureReferenceTemplate.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file is Null..
        /// </summary>
        public static string ConfigFileIsNull {
            get {
                return ResourceManager.GetString("ConfigFileIsNull", resourceCulture);
            }
        }
        
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Used before..
        /// </summary>
        public static string EmailUsedBefore {
            get {
                return ResourceManager.GetString("EmailUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file should have Exactly X Row..
        /// </summary>
        public static string ExcelFileNotCorrect {
            get {
                return ResourceManager.GetString("ExcelFileNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email {0} has been registerd before..
        /// </summary>
        public static string ExistEmailBefore {
            get {
                return ResourceManager.GetString("ExistEmailBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Extention : {0} is not supported..
        /// </summary>
        public static string ExtentionNotSupported {
            get {
                return ResourceManager.GetString("ExtentionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size : {0}mb is high..
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File Template is Not Correct. Please Check All Rows of Table and Compare with Base Template File..
        /// </summary>
        public static string FileTemplateError {
            get {
                return ResourceManager.GetString("FileTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate token Error. Cause: {0}..
        /// </summary>
        public static string GenerateTokenError {
            get {
                return ResourceManager.GetString("GenerateTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Language : {0} is Not Supported..
        /// </summary>
        public static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Not Correct for {0}.
        /// </summary>
        public static string PasswordNotCorrect {
            get {
                return ResourceManager.GetString("PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Pattern is Not Correct..
        /// </summary>
        public static string PasswordPatternError {
            get {
                return ResourceManager.GetString("PasswordPatternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is Empty..
        /// </summary>
        public static string TokenIsEmpty {
            get {
                return ResourceManager.GetString("TokenIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} Was Not Found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
