//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitectureTemplate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitectureTemplate.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file is Null..
        /// </summary>
        public static string ConfigFileIsNull {
            get {
                return ResourceManager.GetString("ConfigFileIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Used before..
        /// </summary>
        public static string EmailUsedBefore {
            get {
                return ResourceManager.GetString("EmailUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with the specified ID was not found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the user creation process..
        /// </summary>
        public static string ErrorDuringCreatingUser {
            get {
                return ResourceManager.GetString("ErrorDuringCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the user {0} registration process..
        /// </summary>
        public static string ErrorDuringRegistringUser {
            get {
                return ResourceManager.GetString("ErrorDuringRegistringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the user {0} Login process..
        /// </summary>
        public static string ErrorDuringUserLogin {
            get {
                return ResourceManager.GetString("ErrorDuringUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during user retrieval by email..
        /// </summary>
        public static string ErrorDuringUserRetrievalByEmail {
            get {
                return ResourceManager.GetString("ErrorDuringUserRetrievalByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during user retrieval by ID from data access..
        /// </summary>
        public static string ErrorDuringUserRetrievalById {
            get {
                return ResourceManager.GetString("ErrorDuringUserRetrievalById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file should have Exactly 42 Row..
        /// </summary>
        public static string ExcelFileNotCorrect {
            get {
                return ResourceManager.GetString("ExcelFileNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email {0} has been registerd before..
        /// </summary>
        public static string ExistEmailBefore {
            get {
                return ResourceManager.GetString("ExistEmailBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Extention : {0} is not supported..
        /// </summary>
        public static string ExtentionNotSupported {
            get {
                return ResourceManager.GetString("ExtentionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add entity {0} to the repository..
        /// </summary>
        public static string FailedToAddEntity {
            get {
                return ResourceManager.GetString("FailedToAddEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete the {0}..
        /// </summary>
        public static string FailedToDeleteEntity {
            get {
                return ResourceManager.GetString("FailedToDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the entities from the repository.
        /// </summary>
        public static string FailedToGetAllEntities {
            get {
                return ResourceManager.GetString("FailedToGetAllEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the {0}..
        /// </summary>
        public static string FailedToGetEntity {
            get {
                return ResourceManager.GetString("FailedToGetEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FaliedToCheckEmail {
            get {
                return ResourceManager.GetString("FaliedToCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size : {0}mb is high..
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File Template is Not Correct. Please Check All Rows of Table and Compare with Base Template File..
        /// </summary>
        public static string FileTemplateError {
            get {
                return ResourceManager.GetString("FileTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the token generation process..
        /// </summary>
        public static string GenerateTokenError {
            get {
                return ResourceManager.GetString("GenerateTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified page size or page index is invalid. Please provide valid values for the page size and page index..
        /// </summary>
        public static string InvalidPageSizePageNumber {
            get {
                return ResourceManager.GetString("InvalidPageSizePageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Language : {0} is Not Supported..
        /// </summary>
        public static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error..
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Not Correct for {0}.
        /// </summary>
        public static string PasswordNotCorrect {
            get {
                return ResourceManager.GetString("PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Pattern is Not Correct..
        /// </summary>
        public static string PasswordPatternError {
            get {
                return ResourceManager.GetString("PasswordPatternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is empty..
        /// </summary>
        public static string TokenIsEmpty {
            get {
                return ResourceManager.GetString("TokenIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the entity {0} in the repository..
        /// </summary>
        public static string UpdateEntityError {
            get {
                return ResourceManager.GetString("UpdateEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified Email: {0} was not found..
        /// </summary>
        public static string UserWithEmailNotFound {
            get {
                return ResourceManager.GetString("UserWithEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the specified ID : {0} was not found..
        /// </summary>
        public static string UserWithIdNotFound {
            get {
                return ResourceManager.GetString("UserWithIdNotFound", resourceCulture);
            }
        }
    }
}
